services:
  db:
    container_name: short_url_db
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=changeme
     - POSTGRES_DB=short_url
  
volumes:
  pgdata:

networks:
  public:
  private: