// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateShortURL(ctx context.Context, arg CreateShortURLParams) (ShortLink, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteShortURL(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetShortURL(ctx context.Context, id int64) (ShortLink, error)
	GetShortURLBySlug(ctx context.Context, slug string) (ShortLink, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListShortURLs(ctx context.Context, arg ListShortURLsParams) ([]ShortLink, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateShortURL(ctx context.Context, arg UpdateShortURLParams) (ShortLink, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
